version: "3.8"

services:
  frontend:
    image: food-frontend
    ports:
      - "80:80"
    networks:
      - foodnet
    deploy:
      replicas: 2

  backend:
    image: food-backend
    networks:
      - foodnet
    deploy:
      replicas: 2

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - foodnet

volumes:
  dbdata:

networks:
  foodnet:
    driver: overlay
